Description of Lorentz_Fit_File
Lorentz_Fit_File
PURPOSE
Lorentz_ Fit_File.m Fits a complex lorentzian function to all of the peaks
SYNOPSIS
function cell_peak_data = Lorentz_Fit_File(cell_x_cor_all, cell_real_cor_all, cell_imag_cor_all, cell_peak_data, cell_fit_options, given_bool)
DESCRIPTION
 Lorentz_ Fit_File.m Fits a complex lorentzian function to all of the peaks
 in a given dataset, returns the arrays of the fit parameters found, and
 coordinates associated with the applied fit function.
 PARAMETERS:
   1. tdms_data:
   2. peak_data:
   3. peak_width:
 RETURN:
   1. Est: [Cell-Array] Each cell contains the 5 calculated fit parameters
   2. fit_x: [Cell-Array] The x-values, associated with the fit that took
                          place for each peak
   3. fit_real: [Cell-Array] The real-values, associated with the fit that
                took place for each peak
   4. fit_imag: [Cell-Array] The x-values, associated with the fit that
                took place for each peak
CROSS-REFERENCE INFORMATION
This function calls:
Lorentz_Fit This function fits a complex lorentzian function to all of the peaks
Lorentz_Fit_Get_Guess LORENTZ_FIT_GUESS: returns the fit parameter guesses for a Lorentzian
Lorentz_Fit_Get_Window LORENTZ_FIT_REGION: Returns the x/y-coordinates, that will be
This function is called by:
Andrew_main % Load TMDS
Process_Data this function sets all of the fields specified by plot_info
SOURCE CODE
function cell_peak_data = Lorentz_Fit_File(cell_x_cor_all, cell_real_cor_all, cell_imag_cor_all, cell_peak_data, cell_fit_options, given_bool)
% Lorentz_ Fit_File.m Fits a complex lorentzian function to all of the peaks
% in a given dataset, returns the arrays of the fit parameters found, and
% coordinates associated with the applied fit function.
%
% PARAMETERS:
%   1. tdms_data:
%   2. peak_data:
%   3. peak_width:
%
% RETURN:
%   1. Est: [Cell-Array] Each cell contains the 5 calculated fit parameters
%   2. fit_x: [Cell-Array] The x-values, associated with the fit that took
%                          place for each peak
%   3. fit_real: [Cell-Array] The real-values, associated with the fit that
%                took place for each peak
%   4. fit_imag: [Cell-Array] The x-values, associated with the fit that
%                took place for each peak
    %fit(length(peak_data)) = struct();
    % perform fit on each peak in each file
    for i = 1:length(cell_peak_data)
        x_cor_all  = cell_x_cor_all{i};
        y_cor_all  = cell_real_cor_all{i} + cell_imag_cor_all{i}.*1i;
        peak_data  = cell_peak_data{i};
        fit_options = cell_fit_options{i};
        % CHECK: if any peaks were found
        if isempty(peak_data)
            continue
        end
        % GET: coordinates to be fit
        [x_cor_fit, y_cor_fit] = Lorentz_Fit_Get_Window( ...
                                x_cor_all, y_cor_all,    ...
                                [peak_data.Frequencies], ...
                                [peak_data.Width],       ...
                                given_bool);
        % Fit Parameters Guess:
        % [A, theta, gamma, f_0, offset]
        guesses = Lorentz_Fit_Get_Guess({peak_data.Frequencies}, ...
                                        {peak_data.signal_x},    ...
                                        {peak_data.signal_y});
        % Perform Fit & assighn variables to be returned
        a = Lorentz_Fit(x_cor_fit, y_cor_fit, guesses, fit_options);
        b = num2cell(a);
        [cell_peak_data{i}.fit] = b{:};
    end
end