function  RUS_data = Get_RUS_Data_Struct(length)
% RETURNS: a structure that is used to store all of the data associated
%          with this program.
% PARAMETER: * length: specifies the lenght of the structure array that           
%                      will be returned.

    % SET: fields for RUS_data struct
    RUS_fields=  { 'file_name'      , ...
                   'temperature'    , ...
                   'signal_x'       , ...
                   'signal_y'       , ...
                   'frequency'      , ...
                   'plot_info'      , ...
                   'peaks_mag_given', ...
                   'peaks_mag_set'  , ...
                   'peaks_tracked'     };
    RUS_fields{2,1} = cell(1,length);
    RUS_data = struct(RUS_fields{:});
    
    % SET: fields for peak_data struct
    peak_fields_set=  { 'Frequencies' , ...
                   'Width'       , ...
                   'signal_x'    , ...
                   'signal_y'    , ...
                   'mag'         , ...
                   'fit'       };
    peak_fields_set{2,1} = [];
    peak = struct(peak_fields_set{:});
    
    [RUS_data.peaks_mag_set] = deal(peak);
    
end

