Description of Magnitude
Magnitude
PURPOSE
Dataplay: returns data added in quadature
SYNOPSIS
function processed_data = Magnitude(x,y)
DESCRIPTION
 Dataplay:  returns data added in quadature
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Get_Given_Peaks ALLOCATE: return value
Get_Set_Peaks sets the peaks to be plotted: using [peakfind] for both
Plot_File This function plots the data from a single tdms file, and uses
SOURCE CODE
function processed_data = Magnitude(x,y)
% Dataplay:  returns data added in quadature
    processed_data = zeros(1,length(x));
    for i = 1:length(x)
        processed_data(i) = sqrt(x(i).^2 + y(i).^2);
    end