function  RUS_data = Get_RUS_Data_Struct(measurements)
% RETURNS: a structure that is used to store all of the data associated
%          with each file.
% PARAMETER: 
%   1. measurments [cell array] of the measurments that are used
%      typically {magnetuc_field, temperature}

    % SET: fields for RUS_data struct
    RUS_fields=  [ 'file_name'      , ...
                   'id'             , ...
                   'plot_info'      , ...
                   measurements     , ...
                   'signal_x'       , ...
                   'signal_y'       , ...
                   'frequency'      , ...
                   'peaks'          , ...
                   'peaks_tracked'     ];
               
    RUS_fields{2,1} = []; % this statement is used so the 
                          % next statement works properly
    RUS_data = struct(RUS_fields{:});
      
    % SET: fields for peak_data struct
    peak_fields_set=  { 'Frequencies' , ...
                   'Width'       , ...
                   'signal_x'    , ...
                   'signal_y'    , ...
                   'mag'         , ...
                   'fit'       };
               
    peak_fields_set{2,1} = [];  % this statement is used so the 
                                % next statement works properly
    peak = struct(peak_fields_set{:});
    
    RUS_data.peaks = peak;
    
end

